[package]
name = "dataframe-rs"
version = "0.1.0"
authors = ["Joey <joey.xf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frunk = "0.3"
frunk_core = "0.3"
